### PR TITLE
Add options view

### PR DESCRIPTION
**Pull request by dsato80**
addressed issue #22

### CODE REVIEW

**Comment by itohtaka** [comment]
Thanks!!, seems this is OK for user testing at CMU. 
But is there any reason why you added "more settings" in NavCog main view but not iPhone > Settings > NavCog? 
It may confusing if settings are placed in two different places

**Comment by dsato80** [comment]
I thought it's similar to "speech", "click", "speech speed".
User might change it "not" rarely.

> If you decide you must provide app settings that users rarely need to change, see The Settings Bundle to learn how to support them in your code. 
> https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Integration.html#//apple_ref/doc/uid/TP40006556-CH61-SW1

**Comment by itohtaka** [comment]
I just discussed with @loopRW about this enhancement. He is OK for user testing with add-options-view branch.
But he also mentioned in order to merge this enhancement to master branch, user interface should be consistent and easy to understand.
“speech”, “click”, “speech speed” should be in "options” with bigger and labeled button.

**Comment by dsato80** [comment]
I agree with you. It can also deal with issue #6.
I think this is the first step of NavCog's user interface changes for next version.
I think "Meter mode" should also be moved into same setting view. 
"Developer mode" is the only setting in the backstage.
Could you check the wiki for new setting view
https://github.com/hulop/NavCogIOS/wiki/Settings

**Pull request merged**
